/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-02-20 10:06:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class dist_005fcity_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1613623701035L));
    _jspx_dependants.put("jar:file:/C:/xampp/htdocs/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Vaccine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write(" ");
 
 if(session.getAttribute("username") == null) {
      response.sendRedirect("login.jsp");
      return ;
   }
    String stateID = request.getParameter("cid");
    int total_vc = 0;
    int alloted=0; 
    int cptotal=0;
    int cwtotal=0;
    int optotal=0;

    try{
        int status = Integer.parseInt(session.getAttribute("statusAdmin").toString());
        pageContext.setAttribute("status", status);

        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/covid","root","");  
        Statement stmt1=conn.createStatement();  
        String sqll ="select * from city where id='"+stateID+"'";
        ResultSet rss= stmt1.executeQuery(sqll);
        while(rss.next()){
            total_vc=rss.getInt("allocated_vaccine");
  
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\r\n");
      out.write("    <meta name=\"description\" content=\"Responsive Admin Template\" />\r\n");
      out.write("    <meta name=\"author\" content=\"SmartUniversity\" />\r\n");
      out.write("    <title>COVID-19 | Local distribution</title>\r\n");
      out.write("    <!-- google font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- icons -->\r\n");
      out.write("    <link href=\"assets/plugins/simple-line-icons/simple-line-icons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"assets/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <!--bootstrap -->\r\n");
      out.write("    <link href=\"assets/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- Material Design Lite CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/plugins/material/material.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/material_style.css\">\r\n");
      out.write("    <!-- animation -->\r\n");
      out.write("    <link href=\"assets/css/pages/animate_page.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- data tables -->\r\n");
      out.write("    <link href=\"assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <!-- Template Styles -->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"assets/css/plugins.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"assets/css/responsive.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"assets/css/theme-color.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- dropzone -->\r\n");
      out.write("    <link href=\"assets/plugins/dropzone/dropzone.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/plugins/material-datetimepicker/bootstrap-material-datetimepicker.css\" />\r\n");
      out.write("    <!-- favicon -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/img/favicon.ico\" /> \r\n");
      out.write("</head>\r\n");
      out.write("<!-- END HEAD -->\r\n");
      out.write("<body class=\"page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-sidebar-color logo-dark\">\r\n");
      out.write("    <div class=\"page-wrapper\">\r\n");
      out.write("        <!-- start header -->\r\n");
      out.write("        <div class=\"page-header navbar navbar-fixed-top\">\r\n");
      out.write("            <div class=\"page-header-inner \">\r\n");
      out.write("                <!-- logo start -->\r\n");
      out.write("                <div class=\"page-logo\">\r\n");
      out.write("                    <a href=\"index.html\">\r\n");
      out.write("                    <img alt=\"\" src=\"assets/img/fla.webp\" >\r\n");
      out.write("                    <!-- <span class=\"logo-default\" >Spice</span> --> </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- logo end -->\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-left in\">\r\n");
      out.write("                    <li><a href=\"#\" class=\"menu-toggler sidebar-toggler\"><i class=\"icon-menu\"></i></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                 <form class=\"search-form-opened\" action=\"#\" method=\"GET\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Search...\" name=\"query\">\r\n");
      out.write("                        <span class=\"input-group-btn search-btn\">\r\n");
      out.write("                          <a href=\"javascript:;\" class=\"btn submit\">\r\n");
      out.write("                             <i class=\"icon-magnifier\"></i>\r\n");
      out.write("                           </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("                <!-- start mobile menu -->\r\n");
      out.write("                <a href=\"javascript:;\" class=\"menu-toggler responsive-toggler\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                </a>\r\n");
      out.write("               <!-- end mobile menu -->\r\n");
      out.write("                <!-- start header menu -->\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end header -->\r\n");
      out.write("        <!-- start page container -->\r\n");
      out.write("        <div class=\"page-container\">\r\n");
      out.write("            <!-- start sidebar menu -->\r\n");
      out.write("            <div class=\"sidebar-container\">\r\n");
      out.write("                <div class=\"sidemenu-container navbar-collapse collapse fixed-menu\">\r\n");
      out.write("                    <div id=\"remove-scroll\">\r\n");
      out.write("                        <ul class=\"sidemenu page-header-fixed p-t-20\" data-keep-expanded=\"false\" data-auto-scroll=\"true\" data-slide-speed=\"200\">\r\n");
      out.write("                            <li class=\"sidebar-toggler-wrapper hide\">\r\n");
      out.write("                                <div class=\"sidebar-toggler\">\r\n");
      out.write("                                    <span></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"sidebar-user-panel\">\r\n");
      out.write("                                <div class=\"user-panel\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                            <div class=\"sidebar-userpic\">\r\n");
      out.write("                                                <img src=\"assets/img/dp.jpg\" class=\"img-responsive\" alt=\"\"> </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"profile-usertitle\">\r\n");
      out.write("                                            <div class=\"sidebar-userpic-name\">Admin Name </div>\r\n");
      out.write("                                            <div class=\"profile-usertitle-job\"> ");
out.println(session.getAttribute("username").toString()); 
      out.write(" </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item start\">\r\n");
      out.write("                                <a href=\"index.jsp\" class=\"nav-link nav-toggle\">\r\n");
      out.write("                                    <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                                    <span class=\"title\">Home</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                             <li class=\"nav-item start\">\r\n");
      out.write("                                <a href=\"dist_city.jsp?sid=1&cid=1\" class=\"nav-link nav-toggle\">\r\n");
      out.write("                                    <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                                    <span class=\"title\">City-wise Distribution</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                            <li class=\"nav-item start\">\r\n");
      out.write("                                <a href=\"addhospital.jsp\" class=\"nav-link nav-toggle\">\r\n");
      out.write("                                    <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                                    <span class=\"title\">Add hospital</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                            <li class=\"nav-item start\">\r\n");
      out.write("                                <a href=\"logout.jsp\" class=\"nav-link nav-toggle\">\r\n");
      out.write("                                    <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                                    <span class=\"title\">Logout</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <!-- end sidebar menu -->\r\n");
      out.write("            <!-- start page content -->\r\n");
      out.write("            <div class=\"page-content-wrapper\">\r\n");
      out.write("                <div class=\"page-content\">\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"page-bar\">\r\n");
      out.write("                        <div class=\"page-title-breadcrumb\">\r\n");
      out.write("                            <div class=\" pull-left\">\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"page-title\">\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                <script>\r\n");
      out.write("                                    function changeTotalNo(){\r\n");
      out.write("                                        document.getElementById('distrubutenow').style.display = \"none\";\r\n");
      out.write("                                        document.getElementById('statetable1').style.display = \"none\";\r\n");
      out.write("                                        document.getElementById('statetable2').style.display = \"block\";\r\n");
      out.write("                                    }\r\n");
      out.write("                                </script>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ol class=\"breadcrumb page-breadcrumb pull-right\">\r\n");
      out.write("                                <li><i class=\"fa fa-home\"></i>&nbsp;<a class=\"parent-item\" href=\"index.html\">Home</a>&nbsp;<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a class=\"parent-item\" href=\"#\">Vaccine</a>&nbsp;<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"active\">Distribution Details</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 p-t-20\"> \r\n");
      out.write("                        <div class=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height txt-full-width\">\r\n");
      out.write("                            <label for=\"simpleFormEmail\">Select City</label>\r\n");
      out.write("                                <select class=\"form-control\" name=\"sel\" id=\"sel\" onchange=\"{doSomething()}\" required>\r\n");
      out.write("                                    ");

                                        Connection conns=DriverManager.getConnection("jdbc:mysql://localhost:3306/covid","root","");  
                                        Statement stmt1s=conns.createStatement();  
                                        String sqlls ="select * from city";
                                        ResultSet rsss= stmt1s.executeQuery(sqlls);
                                        while(rsss.next()){
                                            
                                    
      out.write("\r\n");
      out.write("                                        <option value=\"");
      out.print( rsss.getString(1) );
      out.write('"');
      out.write('>');
      out.print( rsss.getString("name") );
      out.write("</option>\r\n");
      out.write("                                    ");

                                        }
                                    
      out.write("\r\n");
      out.write("                                </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <FORM NAME=\"formState\" METHOD=\"POST\">\r\n");
      out.write("                        <INPUT TYPE=\"HIDDEN\" NAME=\"hiddenButton\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-round btn-primary\" style=\"width: 45%;margin-left: 30px;\" onclick=\"selectState()\">Select</button><br>\r\n");
      out.write("                    </FORM><br><br>\r\n");
      out.write("                    <script>\r\n");
      out.write("                        function selectState(){\r\n");
      out.write("                            var x = $('#sel').val();\r\n");
      out.write("                            window.location.href='./dist_city.jsp?cid='+x;\r\n");
      out.write("                        }\r\n");
      out.write("                    </script>\r\n");
      out.write("                    <div class=\"state-overview\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                                <div class=\"overview-panel purple\">\r\n");
      out.write("                                    <div class=\"symbol\">\r\n");
      out.write("                                        <i class=\"fa fa-users usr-clr\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"value white\">\r\n");
      out.write("                                        <p class=\"sbold addr-font-h1\" data-counter=\"counterup\">\r\n");
      out.write("                                            ");
 out.println(total_vc); 
      out.write("\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>Vaccine in Stock</p>\r\n");
      out.write("                                        ");

                                        }
                                      }
                                 catch(Exception e)
                                 {
                                 System.out.print(e);
                                 e.printStackTrace();
                                 }
                                
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                                <div class=\"overview-panel deepPink-bgcolor\">\r\n");
      out.write("                                    <div class=\"symbol\">\r\n");
      out.write("                                        <i class=\"fa fa-user\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"value white\">\r\n");
      out.write("                                        <p>Distribute Available Vaccine</p>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-round btn-danger\" id=\"distrubutenow\" onclick=\"changeTotalNo()\" style=\"\">Distribute</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                                <div class=\"overview-panel orange\">\r\n");
      out.write("                                    <div class=\"symbol\">\r\n");
      out.write("                                        <i class=\"fa fa-heartbeat\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"value white\">\r\n");
      out.write("                                        <p class=\"sbold addr-font-h1\" data-counter=\"counterup\" data-value=\"14\">0</p>\r\n");
      out.write("                                        <p>People Vaccinated</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"statetable2\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-12\">\r\n");
      out.write("                             <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <div class=\"card card-topline-aqua\">\r\n");
      out.write("                                <div class=\"card-head\">\r\n");
      out.write("                                    <header>BASIC TABLE</header>\r\n");
      out.write("                                    <div class=\"tools\">\r\n");
      out.write("                                        <a class=\"fa fa-repeat btn-color box-refresh\" href=\"javascript:;\"></a>\r\n");
      out.write("                                        <a class=\"t-collapse btn-color fa fa-chevron-down\" href=\"javascript:;\"></a>\r\n");
      out.write("                                        <a class=\"t-close btn-color fa fa-times\" href=\"javascript:;\"></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body \">\r\n");
      out.write("                                  <div class=\"table-scrollable\">\r\n");
      out.write("                                    <table id=\"example4\" class=\"display full-width\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>Name</th>\r\n");
      out.write("                                                <th>Ward Number</th>\r\n");
      out.write("                                                <th>Active Cases</th>\r\n");
      out.write("                                                <th>Corona Warrior</th>\r\n");
      out.write("                                                <th>Other people</th>\r\n");
      out.write("                                                <th>Total Vaccine Sent</th>\r\n");
      out.write("                                                <th>Alloted Vaccine</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                        ");

                                            try
                                            {
                                                Class.forName("com.mysql.jdbc.Driver");
                                                Connection con=DriverManager.getConnection(  
                                                "jdbc:mysql://localhost:3306/covid","root","");  
                                                Statement stmt=con.createStatement();
                                                String sqlfinal="select sum(cp),sum(cw),sum(op) from hospital where c_id='"+stateID+"'"; 
                                                ResultSet rsfinal= stmt.executeQuery(sqlfinal);
                                                while(rsfinal.next()){
                                                    cptotal=rsfinal.getInt(1);
                                                    cwtotal=rsfinal.getInt(2);
                                                    optotal=rsfinal.getInt(3);
                                                } 

                                                String sql ="select * from hospital where c_id='"+stateID+"'";
                                                ResultSet rs= stmt.executeQuery(sql);
                                                while(rs.next()){
                                                int cp=0;
                                                int cw=0;
                                                int op=0;
                                                alloted=(rs.getInt("cp")*60*total_vc)/(100*cptotal)
                                                +(rs.getInt("cw")*25*total_vc)/(100*cwtotal)
                                                +(rs.getInt("op")*15*total_vc)/(100*optotal);
                                            
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>");
      out.print( rs.getString("name") );
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( rs.getString("ward") );
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( rs.getString("cp") );
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( rs.getString("cw") );
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( rs.getString("op") );
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( rs.getString("total_vaccine") );
      out.write("</td>\r\n");
      out.write("                                                <td>");
 out.println(alloted); 
      out.write("</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            ");

                                                }
                                            
                                                } catch (Exception e) {
                                                e.printStackTrace();
                                                }
                                                
      out.write("\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <FORM NAME=\"form1\" METHOD=\"POST\">\r\n");
      out.write("                                    <INPUT TYPE=\"HIDDEN\" NAME=\"buttonName\">\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-round btn-primary\" style=\"width:40%;margin-left:30%;margin-bottom: 20px;\" onclick=\"sendVaccine()\">Send Vaccine</button><br>\r\n");
      out.write("                                </FORM>\r\n");
      out.write("                                ");
 
                                    if(request.getParameter("buttonName") != null) {
                                        int tominus = total_vc;
                                        try
                                        {
                                            Class.forName("com.mysql.jdbc.Driver");
                                            Connection con=DriverManager.getConnection(  
                                            "jdbc:mysql://localhost:3306/covid","root","");  
                                            Statement stmt=con.createStatement();
                                            Statement stmt1=con.createStatement();
                                            String sql ="select * from hospital where c_id='"+stateID+"'";
                                            ResultSet rs= stmt.executeQuery(sql);
                                            while(rs.next()){
                                                int id=rs.getInt("id");
                                                int cp=0;
                                                int cw=0;
                                                int op=0;
                                                int totalvacciness=rs.getInt("total_vaccine");
                                                int vis=rs.getInt("allocated_vaccine");
                                                
                                                int alloteds=(rs.getInt("cp")*60*total_vc)/(100*cptotal)
                                                +(rs.getInt("cw")*25*total_vc)/(100*cwtotal)
                                                +(rs.getInt("op")*15*total_vc)/(100*optotal);
                                                totalvacciness = totalvacciness + alloteds;
                                                vis = vis + alloteds; 
                                                tominus = tominus - alloteds;
                                                String sqls="update hospital set total_vaccine='"+totalvacciness+"',allocated_vaccine='"+vis+"' where id='"+id+"'";
                                                stmt1.executeUpdate(sqls);
                                            }

                                            String sqls="update city set allocated_vaccine='"+tominus+"' where id='"+stateID+"'";
                                            stmt1.executeUpdate(sqls);
                                            response.sendRedirect("./dist_city.jsp?cid="+stateID);
                                        }
                                        catch(Exception e)
                                        {
                                            System.out.print(e);
                                            e.printStackTrace();
                                        }
                                    }
                                
      out.write("\r\n");
      out.write("                                <SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("                                    function sendVaccine()\r\n");
      out.write("                                    {\r\n");
      out.write("                                        document.form1.buttonName.value = \"yes\";\r\n");
      out.write("                                        form1.submit();\r\n");
      out.write("                                    } \r\n");
      out.write("                                </SCRIPT>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"statetable1\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-12\">\r\n");
      out.write("                             <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <div class=\"card card-topline-aqua\">\r\n");
      out.write("                                        <div class=\"card-head\">\r\n");
      out.write("                                            <header>BASIC TABLE</header>\r\n");
      out.write("                                            <div class=\"tools\">\r\n");
      out.write("                                                <a class=\"fa fa-repeat btn-color box-refresh\" href=\"javascript:;\"></a>\r\n");
      out.write("                                                <a class=\"t-collapse btn-color fa fa-chevron-down\" href=\"javascript:;\"></a>\r\n");
      out.write("                                                <a class=\"t-close btn-color fa fa-times\" href=\"javascript:;\"></a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"card-body \">\r\n");
      out.write("                                          <div class=\"table-scrollable\">\r\n");
      out.write("                                            <table id=\"example1\" class=\"display full-width\">\r\n");
      out.write("                                                <thead>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <th>Name</th>\r\n");
      out.write("                                                        <th>Ward Number</th>\r\n");
      out.write("                                                        <th>Active Cases</th>\r\n");
      out.write("                                                        <th>Corona Warrior</th>\r\n");
      out.write("                                                        <th>Other people</th>\r\n");
      out.write("                                                        <th>Total Vaccine Sent</th>\r\n");
      out.write("                                                        <th>Alloted Vaccine</th>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                </thead>\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("                                                ");

                                                    try
                                                    {
                                                        Class.forName("com.mysql.jdbc.Driver");
                                                        Connection con=DriverManager.getConnection(  
                                                        "jdbc:mysql://localhost:3306/covid","root","");  
                                                        Statement stmt=con.createStatement();
                                                        
                                                        String sql ="select * from hospital where c_id='"+stateID+"'";
                                                        ResultSet rs= stmt.executeQuery(sql);
                                                        while(rs.next()){
                                                    
      out.write("\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <td>");
      out.print( rs.getString("name") );
      out.write("</td>\r\n");
      out.write("                                                        <td>");
      out.print( rs.getString("ward") );
      out.write("</td>\r\n");
      out.write("                                                        <td>");
      out.print( rs.getString("cp") );
      out.write("</td>\r\n");
      out.write("                                                        <td>");
      out.print( rs.getString("cw") );
      out.write("</td>\r\n");
      out.write("                                                        <td>");
      out.print( rs.getString("op") );
      out.write("</td>\r\n");
      out.write("                                                        <td>");
      out.print( rs.getString("total_vaccine") );
      out.write("</td>\r\n");
      out.write("                                                        <td>0</td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                    ");

                                                        }
                                                    
                                                        } catch (Exception e) {
                                                            e.printStackTrace();
                                                        }
                                                        
      out.write("\r\n");
      out.write("                                                    </tbody>\r\n");
      out.write("                                                </table>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> \r\n");
      out.write("                    <script>\r\n");
      out.write("                        document.getElementById('statetable1').style.display = \"block\";\r\n");
      out.write("                        document.getElementById('statetable2').style.display = \"none\";\r\n");
      out.write("                    </script>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end page content -->\r\n");
      out.write("            <!-- start chat sidebar -->\r\n");
      out.write("            <div class=\"chat-sidebar-container\" data-close-on-body-click=\"false\">\r\n");
      out.write("                <div class=\"chat-sidebar\">\r\n");
      out.write("                    <ul class=\"nav nav-tabs\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#quick_sidebar_tab_1\" class=\"nav-link active tab-icon\"  data-toggle=\"tab\">Theme\r\n");
      out.write("                                </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#quick_sidebar_tab_2\" class=\"nav-link tab-icon\"  data-toggle=\"tab\"> Chat\r\n");
      out.write("                                </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#quick_sidebar_tab_3\" class=\"nav-link tab-icon\"  data-toggle=\"tab\">  Settings\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"tab-content\">\r\n");
      out.write("                        <div class=\"tab-pane chat-sidebar-settings in show active animated shake\" role=\"tabpanel\" id=\"quick_sidebar_tab_1\">\r\n");
      out.write("                            <div class=\"slimscroll-style\">\r\n");
      out.write("                                <div class=\"theme-light-dark\">\r\n");
      out.write("                                    <h6>Sidebar Theme</h6>\r\n");
      out.write("                                    <button type=\"button\" data-theme=\"white\" class=\"btn lightColor btn-outline btn-circle m-b-10 theme-button\">Light Sidebar</button>\r\n");
      out.write("                                    <button type=\"button\" data-theme=\"dark\" class=\"btn dark btn-outline btn-circle m-b-10 theme-button\">Dark Sidebar</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"theme-light-dark\">\r\n");
      out.write("                                    <h6>Sidebar Color</h6>\r\n");
      out.write("                                    <ul class=\"list-unstyled\">\r\n");
      out.write("                                        <li class=\"complete\">\r\n");
      out.write("                                            <div class=\"theme-color sidebar-theme\">\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"white\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"dark\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"blue\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"indigo\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"cyan\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"green\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"red\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <h6>Header Brand color</h6>\r\n");
      out.write("                                    <ul class=\"list-unstyled\">\r\n");
      out.write("                                        <li class=\"theme-option\">\r\n");
      out.write("                                            <div class=\"theme-color logo-theme\">\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"logo-white\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"logo-dark\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"logo-blue\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"logo-indigo\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"logo-cyan\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"logo-green\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"logo-red\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <h6>Header color</h6>\r\n");
      out.write("                                    <ul class=\"list-unstyled\">\r\n");
      out.write("                                        <li class=\"theme-option\">\r\n");
      out.write("                                            <div class=\"theme-color header-theme\">\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"header-white\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"header-dark\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"header-blue\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"header-indigo\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"header-cyan\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"header-green\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                                <a href=\"#\" data-theme=\"header-red\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       \r\n");
      out.write("                        <!-- Start Setting Panel --> \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end chat sidebar -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end page container -->\r\n");
      out.write("        <!-- start footer -->\r\n");
      out.write("        <div class=\"page-footer\">\r\n");
      out.write("            <div class=\"page-footer-inner\"> 2020 &copy; Deepanshu Pathak\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"scroll-to-top\">\r\n");
      out.write("                <i class=\"icon-arrow-up\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end footer -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- start js include path -->\r\n");
      out.write("    <script src=\"assets/plugins/jquery/jquery.min.js\" ></script>\r\n");
      out.write("    <script src=\"assets/plugins/popper/popper.min.js\" ></script>\r\n");
      out.write("    <script src=\"assets/plugins/jquery-blockui/jquery.blockui.min.js\" ></script>\r\n");
      out.write("    <script src=\"assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("    <script src=\"assets/plugins/bootstrap/js/bootstrap.min.js\" ></script>\r\n");
      out.write("    <!-- Common js-->\r\n");
      out.write("    <script src=\"assets/js/app.js\" ></script>\r\n");
      out.write("    <script src=\"assets/js/layout.js\" ></script>\r\n");
      out.write("    <script src=\"assets/js/theme-color.js\" ></script>\r\n");
      out.write("    <!-- Material -->\r\n");
      out.write("    <script src=\"assets/plugins/material/material.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/pages/material_select/getmdl-select.js\" ></script>\r\n");
      out.write("    <script  src=\"assets/plugins/material-datetimepicker/moment-with-locales.min.js\"></script>\r\n");
      out.write("    <script  src=\"assets/plugins/material-datetimepicker/bootstrap-material-datetimepicker.js\"></script>\r\n");
      out.write("    <script  src=\"assets/plugins/material-datetimepicker/datetimepicker.js\"></script>\r\n");
      out.write("    <!-- dropzone -->\r\n");
      out.write("    <script src=\"assets/plugins/dropzone/dropzone.js\" ></script>\r\n");
      out.write("    <script src=\"assets/plugins/dropzone/dropzone-call.js\" ></script>\r\n");
      out.write("    <!-- animation -->\r\n");
      out.write("    <script src=\"assets/js/pages/ui/animations.js\" ></script>\r\n");
      out.write("    <!-- end js include path -->\r\n");
      out.write("    <!-- data tables -->\r\n");
      out.write("    <script src=\"assets/plugins/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.js\" ></script>\r\n");
      out.write("    <script src=\"assets/js/pages/table/table_data.js\" ></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from radixtouch.in/templates/admin/hotel/source/add_room.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Apr 2018 06:56:54 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /dist_city.jsp(30,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("status");
      // /dist_city.jsp(30,2) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("session");
      // /dist_city.jsp(30,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/dist_city.jsp(30,2) '${status}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${status}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /dist_city.jsp(134,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                 <li class=\"nav-item start\">\r\n");
          out.write("                                    <a href=\"addvaccine.html\" class=\"nav-link nav-toggle\">\r\n");
          out.write("                                        <i class=\"material-icons\">dashboard</i>\r\n");
          out.write("                                        <span class=\"title\">Add Vaccine</span>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /dist_city.jsp(142,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"nav-item start\">\r\n");
          out.write("                                    <a href=\"dist_vaccine.jsp\" class=\"nav-link nav-toggle\">\r\n");
          out.write("                                        <i class=\"material-icons\">dashboard</i>\r\n");
          out.write("                                        <span class=\"title\">Universal Distribution</span>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /dist_city.jsp(150,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status != 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"nav-item start\">\r\n");
          out.write("                                    <a href=\"dist_state.jsp?sid=1\" class=\"nav-link nav-toggle\">\r\n");
          out.write("                                        <i class=\"material-icons\">dashboard</i>\r\n");
          out.write("                                        <span class=\"title\">State-wise Distribution</span>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /dist_city.jsp(164,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"nav-item start\">\r\n");
          out.write("                                    <a href=\"addstate.html\" class=\"nav-link nav-toggle\">\r\n");
          out.write("                                        <i class=\"material-icons\">dashboard</i>\r\n");
          out.write("                                        <span class=\"title\">Add State</span>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /dist_city.jsp(172,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status != 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"nav-item start\">\r\n");
          out.write("                                    <a href=\"addcity2.jsp\" class=\"nav-link nav-toggle\">\r\n");
          out.write("                                        <i class=\"material-icons\">dashboard</i>\r\n");
          out.write("                                        <span class=\"title\">Add City</span>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /dist_city.jsp(186,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status == 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <li class=\"nav-item start\">\r\n");
          out.write("                                    <a href=\"userlist.jsp\" class=\"nav-link nav-toggle\">\r\n");
          out.write("                                        <i class=\"material-icons\">dashboard</i>\r\n");
          out.write("                                        <span class=\"title\">User List</span>\r\n");
          out.write("                                    </a>\r\n");
          out.write("                                </li>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }
}
