/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-02-18 09:14:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class slogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<!-- BEGIN HEAD -->\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from radixtouch.in/templates/admin/hotel/source/add_room.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Apr 2018 06:56:54 GMT -->\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\" />\r\n");
      out.write("    <meta name=\"description\" content=\"Responsive Admin Template\" />\r\n");
      out.write("    <meta name=\"author\" content=\"SmartUniversity\" />\r\n");
      out.write("    <title>COVID-19 |State Login</title>\r\n");
      out.write("    <!-- google font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<!-- icons -->\r\n");
      out.write("    <link href=\"assets/plugins/simple-line-icons/simple-line-icons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"assets/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<!--bootstrap -->\r\n");
      out.write("\t<link href=\"assets/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <!-- Material Design Lite CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/plugins/material/material.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/material_style.css\">\r\n");
      out.write("\t<!-- animation -->\r\n");
      out.write("\t<link href=\"assets/css/pages/animate_page.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- Template Styles -->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"assets/css/plugins.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"assets/css/responsive.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"assets/css/theme-color.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<!-- dropzone -->\r\n");
      out.write("    <link href=\"assets/plugins/dropzone/dropzone.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("    <!-- Date Time item CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/plugins/material-datetimepicker/bootstrap-material-datetimepicker.css\" />\r\n");
      out.write("\t<!-- favicon -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"assets/img/favicon.ico\" /> \r\n");
      out.write("</head>\r\n");
      out.write("<!-- END HEAD -->\r\n");
      out.write("<body class=\"page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-sidebar-color logo-dark\">\r\n");
      out.write("    <div class=\"page-wrapper\">\r\n");
      out.write("        <!-- start header -->\r\n");
      out.write("\t\t<div class=\"page-header navbar navbar-fixed-top\">\r\n");
      out.write("            <div class=\"page-header-inner \">\r\n");
      out.write("                <!-- logo start -->\r\n");
      out.write("                <div class=\"page-logo\">\r\n");
      out.write("                    <a href=\"index.html\">\r\n");
      out.write("                    <img alt=\"\" src=\"assets/img/fla.webp\" >\r\n");
      out.write("                    <!-- <span class=\"logo-default\" >Spice</span> --> </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- logo end -->\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-left in\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"menu-toggler sidebar-toggler\"><i class=\"icon-menu\"></i></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("                 <form class=\"search-form-opened\" action=\"#\" method=\"GET\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Search...\" name=\"query\">\r\n");
      out.write("                        <span class=\"input-group-btn search-btn\">\r\n");
      out.write("                          <a href=\"javascript:;\" class=\"btn submit\">\r\n");
      out.write("                             <i class=\"icon-magnifier\"></i>\r\n");
      out.write("                           </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("                <!-- start mobile menu -->\r\n");
      out.write("                <a href=\"javascript:;\" class=\"menu-toggler responsive-toggler\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                </a>\r\n");
      out.write("               <!-- end mobile menu -->\r\n");
      out.write("                <!-- start header menu -->\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end header -->\r\n");
      out.write("        <!-- start page container -->\r\n");
      out.write("        <div class=\"page-container\">\r\n");
      out.write(" \t\t\t<!-- start sidebar menu -->\r\n");
      out.write(" \t\t\t<div class=\"sidebar-container\">\r\n");
      out.write("                <div class=\"sidemenu-container navbar-collapse collapse fixed-menu\">\r\n");
      out.write("                    <div id=\"remove-scroll\">\r\n");
      out.write("                        <ul class=\"sidemenu page-header-fixed p-t-20\" data-keep-expanded=\"false\" data-auto-scroll=\"true\" data-slide-speed=\"200\">\r\n");
      out.write("                            <li class=\"sidebar-toggler-wrapper hide\">\r\n");
      out.write("                                <div class=\"sidebar-toggler\">\r\n");
      out.write("                                    <span></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"sidebar-user-panel\">\r\n");
      out.write("                                <div class=\"user-panel\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                            <div class=\"sidebar-userpic\">\r\n");
      out.write("                                                <img src=\"assets/img/dp.jpg\" class=\"img-responsive\" alt=\"\"> </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"profile-usertitle\">\r\n");
      out.write("                                            <div class=\"sidebar-userpic-name\">State Name </div>\r\n");
      out.write("                                            <div class=\"profile-usertitle-job\"> State </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item start\">\r\n");
      out.write("                                <a href=\"login.jsp\" class=\"nav-link nav-toggle\">\r\n");
      out.write("                                    <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                                    <span class=\"title\">Admin Login</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item start\">\r\n");
      out.write("                                <a href=\"slogin.jsp\" class=\"nav-link nav-toggle\">\r\n");
      out.write("                                    <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                                    <span class=\"title\">State Login</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                             <li class=\"nav-item start\">\r\n");
      out.write("                                <a href=\"clogin.jsp\" class=\"nav-link nav-toggle\">\r\n");
      out.write("                                    <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                                    <span class=\"title\">City Login</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item start\">\r\n");
      out.write("                                <a href=\"hlogin.jsp\" class=\"nav-link nav-toggle\">\r\n");
      out.write("                                    <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                                    <span class=\"title\">Hospital Login</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t <!-- end sidebar menu -->\r\n");
      out.write("\t\t\t<!-- start page content -->\r\n");
      out.write("            <div class=\"page-content-wrapper\">\r\n");
      out.write("                <div class=\"page-content\">\r\n");
      out.write("                    <div class=\"page-bar\">\r\n");
      out.write("                        <div class=\"page-title-breadcrumb\">\r\n");
      out.write("                            <div class=\" pull-left\">\r\n");
      out.write("                                <div class=\"page-title\">State Login</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ol class=\"breadcrumb page-breadcrumb pull-right\">\r\n");
      out.write("                                <li><i class=\"fa fa-home\"></i>&nbsp;<a class=\"parent-item\" href=\"index.html\">Home</a>&nbsp;<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a class=\"parent-item\" href=\"#\">State Login</a>&nbsp;<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"active\">Fill  Details</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-head\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<header></header>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"slogindb.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body row\">\r\n");
      out.write("                                    <div class=\"col-lg-6 p-t-20\"> \r\n");
      out.write("                                      <div class = \"mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width\">\r\n");
      out.write("                                         <input class = \"mdl-textfield__input\" type = \"text\" name=\"name\">\r\n");
      out.write("                                         <label class = \"mdl-textfield__label\">Enter Userame</label>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div></div>\r\n");
      out.write("                                    <div class=\"card-body row\">\r\n");
      out.write("\t\t\t\t\t\t            <div class=\"col-lg-6 p-t-20\"> \r\n");
      out.write("\t\t\t\t\t\t              <div class = \"mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width\">\r\n");
      out.write("                                         <input class = \"mdl-textfield__input\" type = \"password\" name=\"password\">\r\n");
      out.write("                                         <label class = \"mdl-textfield__label\">Enter Password</label>\r\n");
      out.write("                                      </div>\r\n");
      out.write("\t\t\t\t\t\t           \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t         <div class=\"col-lg-12 p-t-20 text-center\"> \r\n");
      out.write("\t\t\t\t\t\t              \t<button type=\"submit\" name=\"submit\" id=\"submit\" value=\"submit\" class=\"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default\">Cancel</button>\r\n");
      out.write("\t\t\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end page content -->\r\n");
      out.write("            <!-- start chat sidebar -->\r\n");
      out.write("            <div class=\"chat-sidebar-container\" data-close-on-body-click=\"false\">\r\n");
      out.write("                <div class=\"chat-sidebar\">\r\n");
      out.write("                    <ul class=\"nav nav-tabs\">\r\n");
      out.write("                    \t<li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#quick_sidebar_tab_1\" class=\"nav-link active tab-icon\"  data-toggle=\"tab\">Theme\r\n");
      out.write("                                </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#quick_sidebar_tab_2\" class=\"nav-link tab-icon\"  data-toggle=\"tab\"> Chat\r\n");
      out.write("                                </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"#quick_sidebar_tab_3\" class=\"nav-link tab-icon\"  data-toggle=\"tab\">  Settings\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"tab-content\">\r\n");
      out.write("                    \t<div class=\"tab-pane chat-sidebar-settings in show active animated shake\" role=\"tabpanel\" id=\"quick_sidebar_tab_1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"slimscroll-style\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"theme-light-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6>Sidebar Theme</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" data-theme=\"white\" class=\"btn lightColor btn-outline btn-circle m-b-10 theme-button\">Light Sidebar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" data-theme=\"dark\" class=\"btn dark btn-outline btn-circle m-b-10 theme-button\">Dark Sidebar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"theme-light-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6>Sidebar Color</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"complete\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"theme-color sidebar-theme\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"white\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"dark\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"blue\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"indigo\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"cyan\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"green\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"red\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6>Header Brand color</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"theme-option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"theme-color logo-theme\">\r\n");
      out.write("\t\t\t\t\t\t\t\t             \t<a href=\"#\" data-theme=\"logo-white\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"logo-dark\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"logo-blue\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"logo-indigo\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"logo-cyan\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"logo-green\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-theme=\"logo-red\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t           \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6>Header color</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"theme-option\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"theme-color header-theme\">\r\n");
      out.write("\t\t\t\t\t\t\t\t             \t<a href=\"#\" data-theme=\"header-white\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t             \t<a href=\"#\" data-theme=\"header-dark\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t             \t<a href=\"#\" data-theme=\"header-blue\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t             \t<a href=\"#\" data-theme=\"header-indigo\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t             \t<a href=\"#\" data-theme=\"header-cyan\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t             \t<a href=\"#\" data-theme=\"header-green\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t             \t<a href=\"#\" data-theme=\"header-red\"><span class=\"head\"></span><span class=\"cont\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t          \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                        <!-- Start Doctor Chat --> \r\n");
      out.write(" \t\t\t\t\t\t<div class=\"tab-pane chat-sidebar-chat animated slideInRight\" id=\"quick_sidebar_tab_2\">\r\n");
      out.write("                        \t<div class=\"chat-sidebar-list\">\r\n");
      out.write("\t                            <div class=\"chat-sidebar-chat-users slimscroll-style\" data-rail-color=\"#ddd\" data-wrapper-class=\"chat-sidebar-list\">\r\n");
      out.write("\t                                <div class=\"chat-header\"><h5 class=\"list-heading\">Online</h5></div>\r\n");
      out.write("\t                                <ul class=\"media-list list-items\">\r\n");
      out.write("\t                                    <li class=\"media\"><img class=\"media-object\" src=\"assets/img/user/user3.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"online dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">John Deo</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Spine Surgeon</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                    <li class=\"media\">\r\n");
      out.write("\t                                        <div class=\"media-status\">\r\n");
      out.write("\t                                            <span class=\"badge badge-success\">5</span>\r\n");
      out.write("\t                                        </div> <img class=\"media-object\" src=\"assets/img/user/user1.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"busy dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Rajesh</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Director</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                    <li class=\"media\"><img class=\"media-object\" src=\"assets/img/user/user5.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"away dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Jacob Ryan</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Ortho Surgeon</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                    <li class=\"media\">\r\n");
      out.write("\t                                        <div class=\"media-status\">\r\n");
      out.write("\t                                            <span class=\"badge badge-danger\">8</span>\r\n");
      out.write("\t                                        </div> <img class=\"media-object\" src=\"assets/img/user/user4.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"online dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Kehn Anderson</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">CEO</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                    <li class=\"media\"><img class=\"media-object\" src=\"assets/img/user/user2.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"busy dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Sarah Smith</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Anaesthetics</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                    <li class=\"media\"><img class=\"media-object\" src=\"assets/img/user/user7.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"online dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Vlad Cardella</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Cardiologist</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                </ul>\r\n");
      out.write("\t                                <div class=\"chat-header\"><h5 class=\"list-heading\">Offline</h5></div>\r\n");
      out.write("\t                                <ul class=\"media-list list-items\">\r\n");
      out.write("\t                                    <li class=\"media\">\r\n");
      out.write("\t                                        <div class=\"media-status\">\r\n");
      out.write("\t                                            <span class=\"badge badge-warning\">4</span>\r\n");
      out.write("\t                                        </div> <img class=\"media-object\" src=\"assets/img/user/user6.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"offline dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Jennifer Maklen</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Nurse</div>\r\n");
      out.write("\t                                            <div class=\"media-heading-small\">Last seen 01:20 AM</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                    <li class=\"media\"><img class=\"media-object\" src=\"assets/img/user/user8.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"offline dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Lina Smith</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Ortho Surgeon</div>\r\n");
      out.write("\t                                            <div class=\"media-heading-small\">Last seen 11:14 PM</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                    <li class=\"media\">\r\n");
      out.write("\t                                        <div class=\"media-status\">\r\n");
      out.write("\t                                            <span class=\"badge badge-success\">9</span>\r\n");
      out.write("\t                                        </div> <img class=\"media-object\" src=\"assets/img/user/user9.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"offline dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Jeff Adam</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Compounder</div>\r\n");
      out.write("\t                                            <div class=\"media-heading-small\">Last seen 3:31 PM</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                    <li class=\"media\"><img class=\"media-object\" src=\"assets/img/user/user10.jpg\" width=\"35\" height=\"35\" alt=\"...\">\r\n");
      out.write("\t                                        <i class=\"offline dot\"></i>\r\n");
      out.write("\t                                        <div class=\"media-body\">\r\n");
      out.write("\t                                            <h5 class=\"media-heading\">Anjelina Cardella</h5>\r\n");
      out.write("\t                                            <div class=\"media-heading-sub\">Physiotherapist</div>\r\n");
      out.write("\t                                            <div class=\"media-heading-small\">Last seen 7:45 PM</div>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("\t                                    </li>\r\n");
      out.write("\t                                </ul>\r\n");
      out.write("\t                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"chat-sidebar-item\">\r\n");
      out.write("                                <div class=\"chat-sidebar-chat-user\">\r\n");
      out.write("                                    <div class=\"page-quick-sidemenu\">\r\n");
      out.write("                                        <a href=\"javascript:;\" class=\"chat-sidebar-back-to-list\">\r\n");
      out.write("                                            <i class=\"fa fa-angle-double-left\"></i>Back\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"chat-sidebar-chat-user-messages\">\r\n");
      out.write("                                        <div class=\"post out\">\r\n");
      out.write("                                            <img class=\"avatar\" alt=\"\" src=\"assets/img/dp.jpg\" />\r\n");
      out.write("                                            <div class=\"message\">\r\n");
      out.write("                                                <span class=\"arrow\"></span> <a href=\"javascript:;\" class=\"name\">Kiran Patel</a> <span class=\"datetime\">9:10</span>\r\n");
      out.write("                                                <span class=\"body-out\"> could you send me menu icons ? </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"post in\">\r\n");
      out.write("                                            <img class=\"avatar\" alt=\"\" src=\"assets/img/user/user5.jpg\" />\r\n");
      out.write("                                            <div class=\"message\">\r\n");
      out.write("                                                <span class=\"arrow\"></span> <a href=\"javascript:;\" class=\"name\">Jacob Ryan</a> <span class=\"datetime\">9:10</span>\r\n");
      out.write("                                                <span class=\"body\"> please give me 10 minutes. </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"post out\">\r\n");
      out.write("                                            <img class=\"avatar\" alt=\"\" src=\"assets/img/dp.jpg\" />\r\n");
      out.write("                                            <div class=\"message\">\r\n");
      out.write("                                                <span class=\"arrow\"></span> <a href=\"javascript:;\" class=\"name\">Kiran Patel</a> <span class=\"datetime\">9:11</span>\r\n");
      out.write("                                                <span class=\"body-out\"> ok fine :) </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"post in\">\r\n");
      out.write("                                            <img class=\"avatar\" alt=\"\" src=\"assets/img/user/user5.jpg\" />\r\n");
      out.write("                                            <div class=\"message\">\r\n");
      out.write("                                                <span class=\"arrow\"></span> <a href=\"javascript:;\" class=\"name\">Jacob Ryan</a> <span class=\"datetime\">9:22</span>\r\n");
      out.write("                                                <span class=\"body\">Sorry for\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthe delay. i sent mail to you. let me know if it is ok or not.</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"post out\">\r\n");
      out.write("                                            <img class=\"avatar\" alt=\"\" src=\"assets/img/dp.jpg\" />\r\n");
      out.write("                                            <div class=\"message\">\r\n");
      out.write("                                                <span class=\"arrow\"></span> <a href=\"javascript:;\" class=\"name\">Kiran Patel</a> <span class=\"datetime\">9:26</span>\r\n");
      out.write("                                                <span class=\"body-out\"> it is perfect! :) </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"post out\">\r\n");
      out.write("                                            <img class=\"avatar\" alt=\"\" src=\"assets/img/dp.jpg\" />\r\n");
      out.write("                                            <div class=\"message\">\r\n");
      out.write("                                                <span class=\"arrow\"></span> <a href=\"javascript:;\" class=\"name\">Kiran Patel</a> <span class=\"datetime\">9:26</span>\r\n");
      out.write("                                                <span class=\"body-out\"> Great! Thanks. </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"post in\">\r\n");
      out.write("                                            <img class=\"avatar\" alt=\"\" src=\"assets/img/user/user5.jpg\" />\r\n");
      out.write("                                            <div class=\"message\">\r\n");
      out.write("                                                <span class=\"arrow\"></span> <a href=\"javascript:;\" class=\"name\">Jacob Ryan</a> <span class=\"datetime\">9:27</span>\r\n");
      out.write("                                                <span class=\"body\"> it is my pleasure :) </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"chat-sidebar-chat-user-form\">\r\n");
      out.write("                                        <div class=\"input-group\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"Type a message here...\">\r\n");
      out.write("                                            <div class=\"input-group-btn\">\r\n");
      out.write("                                                <button type=\"button\" class=\"btn deepPink-bgcolor\">\r\n");
      out.write("                                                    <i class=\"fa fa-arrow-right\"></i>\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- End Doctor Chat --> \r\n");
      out.write(" \t\t\t\t\t\t<!-- Start Setting Panel --> \r\n");
      out.write(" \t\t\t\t\t\t<div class=\"tab-pane chat-sidebar-settings animated slideInUp\" id=\"quick_sidebar_tab_3\">\r\n");
      out.write("                            <div class=\"chat-sidebar-settings-list slimscroll-style\">\r\n");
      out.write("                                <div class=\"chat-header\"><h5 class=\"list-heading\">Layout Settings</h5></div>\r\n");
      out.write("\t                            <div class=\"chatpane inner-content \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"settings-list\">\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Sidebar Position</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                           <select class=\"sidebar-pos-option form-control input-inline input-sm input-small \">\r\n");
      out.write("\t                                                <option value=\"left\" selected=\"selected\">Left</option>\r\n");
      out.write("\t                                                <option value=\"right\">Right</option>\r\n");
      out.write("                                            \t</select>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Header</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                           <select class=\"page-header-option form-control input-inline input-sm input-small \">\r\n");
      out.write("\t                                                <option value=\"fixed\" selected=\"selected\">Fixed</option>\r\n");
      out.write("\t                                                <option value=\"default\">Default</option>\r\n");
      out.write("                                            \t</select>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Sidebar Menu </div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                           <select class=\"sidebar-menu-option form-control input-inline input-sm input-small \">\r\n");
      out.write("\t                                                <option value=\"accordion\" selected=\"selected\">Accordion</option>\r\n");
      out.write("\t                                                <option value=\"hover\">Hover</option>\r\n");
      out.write("                                            \t</select>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Footer</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                           <select class=\"page-footer-option form-control input-inline input-sm input-small \">\r\n");
      out.write("\t                                                <option value=\"fixed\">Fixed</option>\r\n");
      out.write("\t                                                <option value=\"default\" selected=\"selected\">Default</option>\r\n");
      out.write("                                            \t</select>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"chat-header\"><h5 class=\"list-heading\">Account Settings</h5></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"settings-list\">\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Notifications</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                            <div class=\"switch\">\r\n");
      out.write("\t\t\t\t\t                                <label class = \"mdl-switch mdl-js-switch mdl-js-ripple-effect\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  for = \"switch-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  <input type = \"checkbox\" id = \"switch-1\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                     class = \"mdl-switch__input\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t               \t</label>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Show Online</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                            <div class=\"switch\">\r\n");
      out.write("\t\t\t\t\t                                <label class = \"mdl-switch mdl-js-switch mdl-js-ripple-effect\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  for = \"switch-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  <input type = \"checkbox\" id = \"switch-7\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                     class = \"mdl-switch__input\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t               \t</label>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Status</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                            <div class=\"switch\">\r\n");
      out.write("\t\t\t\t\t                                <label class = \"mdl-switch mdl-js-switch mdl-js-ripple-effect\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  for = \"switch-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  <input type = \"checkbox\" id = \"switch-2\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                     class = \"mdl-switch__input\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t               \t</label>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">2 Steps Verification</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                            <div class=\"switch\">\r\n");
      out.write("\t\t\t\t\t                                <label class = \"mdl-switch mdl-js-switch mdl-js-ripple-effect\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  for = \"switch-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  <input type = \"checkbox\" id = \"switch-3\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                     class = \"mdl-switch__input\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t               \t</label>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                </div>\r\n");
      out.write("                                    <div class=\"chat-header\"><h5 class=\"list-heading\">General Settings</h5></div>\r\n");
      out.write("                                    <div class=\"settings-list\">\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Location</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                            <div class=\"switch\">\r\n");
      out.write("\t\t\t\t\t                                <label class = \"mdl-switch mdl-js-switch mdl-js-ripple-effect\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  for = \"switch-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  <input type = \"checkbox\" id = \"switch-4\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                     class = \"mdl-switch__input\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t               \t</label>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Save Histry</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                            <div class=\"switch\">\r\n");
      out.write("\t\t\t\t\t                                <label class = \"mdl-switch mdl-js-switch mdl-js-ripple-effect\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  for = \"switch-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  <input type = \"checkbox\" id = \"switch-5\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                     class = \"mdl-switch__input\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t               \t</label>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                    <div class=\"setting-item\">\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-text\">Auto Updates</div>\r\n");
      out.write("\t\t\t\t\t                        <div class=\"setting-set\">\r\n");
      out.write("\t\t\t\t\t                            <div class=\"switch\">\r\n");
      out.write("\t\t\t\t\t                                <label class = \"mdl-switch mdl-js-switch mdl-js-ripple-effect\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  for = \"switch-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                  <input type = \"checkbox\" id = \"switch-6\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                     class = \"mdl-switch__input\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t               \t</label>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t                </div>\r\n");
      out.write("\t                        \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end chat sidebar -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end page container -->\r\n");
      out.write("        <!-- start footer -->\r\n");
      out.write("        <div class=\"page-footer\">\r\n");
      out.write("            <div class=\"page-footer-inner\"> 2018 &copy; Spice Hotel Template By\r\n");
      out.write("                <a href=\"mailto:redstartheme@gmail.com\" target=\"_top\" class=\"makerCss\">RedStar Theme</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"scroll-to-top\">\r\n");
      out.write("                <i class=\"icon-arrow-up\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end footer -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- start js include path -->\r\n");
      out.write("    <script src=\"assets/plugins/jquery/jquery.min.js\" ></script>\r\n");
      out.write("    <script src=\"assets/plugins/popper/popper.min.js\" ></script>\r\n");
      out.write("    <script src=\"assets/plugins/jquery-blockui/jquery.blockui.min.js\" ></script>\r\n");
      out.write("\t<script src=\"assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("    <script src=\"assets/plugins/bootstrap/js/bootstrap.min.js\" ></script>\r\n");
      out.write("    <!-- Common js-->\r\n");
      out.write("\t<script src=\"assets/js/app.js\" ></script>\r\n");
      out.write("    <script src=\"assets/js/layout.js\" ></script>\r\n");
      out.write("\t<script src=\"assets/js/theme-color.js\" ></script>\r\n");
      out.write("\t<!-- Material -->\r\n");
      out.write("\t<script src=\"assets/plugins/material/material.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/pages/material_select/getmdl-select.js\" ></script>\r\n");
      out.write("    <script  src=\"assets/plugins/material-datetimepicker/moment-with-locales.min.js\"></script>\r\n");
      out.write("\t<script  src=\"assets/plugins/material-datetimepicker/bootstrap-material-datetimepicker.js\"></script>\r\n");
      out.write("\t<script  src=\"assets/plugins/material-datetimepicker/datetimepicker.js\"></script>\r\n");
      out.write("    <!-- dropzone -->\r\n");
      out.write("    <script src=\"assets/plugins/dropzone/dropzone.js\" ></script>\r\n");
      out.write("    <script src=\"assets/plugins/dropzone/dropzone-call.js\" ></script>\r\n");
      out.write("\t<!-- animation -->\r\n");
      out.write("\t<script src=\"assets/js/pages/ui/animations.js\" ></script>\r\n");
      out.write("    <!-- end js include path -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from radixtouch.in/templates/admin/hotel/source/add_room.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Apr 2018 06:56:54 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
